"""phaseA_violation_client_ref

Revision ID: 0cd4fb95ceaf
Revises: 90db7a4e87e6
Create Date: 2026-09-16 10:49:49.884562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

revision: str = '0cd4fb95ceaf'
down_revision: Union[str, None] = '90db7a4e87e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violations', sa.Column('client_ref', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_violations_client_ref'), 'violations', ['client_ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violations_client_ref'), table_name='violations')
    op.drop_column('violations', 'client_ref')
    # ### end Alembic commands ###