"""phaseB_files_image

Revision ID: 1b4d2025348d
Revises: 0cd4fb95ceaf
Create Date: 2026-09-16 11:08:50.125144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

revision: str = '1b4d2025348d'
down_revision: Union[str, None] = '0cd4fb95ceaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('storage_provider', sa.String(length=16), nullable=False),
    sa.Column('bucket', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=256), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('client_ref', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_client_ref'), 'files', ['client_ref'], unique=True)
    op.create_index(op.f('ix_files_object_key'), 'files', ['object_key'], unique=True)
    op.add_column('violations', sa.Column('image_file_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_violations_image_file_id'), 'violations', ['image_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violations_image_file_id'), table_name='violations')
    op.drop_column('violations', 'image_file_id')
    op.drop_index(op.f('ix_files_object_key'), table_name='files')
    op.drop_index(op.f('ix_files_client_ref'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###