"""phase3_vehicles_permits

Revision ID: 395a9aba608d
Revises: 2a93191a882a
Create Date: 2026-09-16 07:05:23.516671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

revision: str = '395a9aba608d'
down_revision: Union[str, None] = '2a93191a882a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_person_id', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('plate_raw', sa.String(length=64), nullable=False),
    sa.Column('plate_normalized', sa.String(length=32), nullable=False),
    sa.Column('plate_type', sa.String(length=16), nullable=False),
    sa.Column('vehicle_type', sa.String(length=16), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_owner_person_id'), 'vehicles', ['owner_person_id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_normalized'), 'vehicles', ['plate_normalized'], unique=False)
    op.create_index(op.f('ix_vehicles_unit_id'), 'vehicles', ['unit_id'], unique=False)
    op.create_table('access_permits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('plate_normalized', sa.String(length=32), nullable=False),
    sa.Column('host_unit_id', sa.String(length=36), nullable=True),
    sa.Column('permit_type', sa.String(length=24), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_days', sa.Text(), nullable=True),
    sa.Column('allowed_from_time', sa.String(length=8), nullable=True),
    sa.Column('allowed_until_time', sa.String(length=8), nullable=True),
    sa.Column('max_entries', sa.Integer(), nullable=True),
    sa.Column('used_entries', sa.Integer(), nullable=False),
    sa.Column('allowed_gate_ids', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issued_by', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_permits_plate_normalized'), 'access_permits', ['plate_normalized'], unique=False)
    op.create_index(op.f('ix_access_permits_status'), 'access_permits', ['status'], unique=False)
    op.create_index(op.f('ix_access_permits_vehicle_id'), 'access_permits', ['vehicle_id'], unique=False)
    op.create_table('vehicle_restrictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('plate_normalized', sa.String(length=32), nullable=False),
    sa.Column('restriction_type', sa.String(length=24), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_restrictions_plate_normalized'), 'vehicle_restrictions', ['plate_normalized'], unique=False)
    op.create_index(op.f('ix_vehicle_restrictions_status'), 'vehicle_restrictions', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_restrictions_vehicle_id'), 'vehicle_restrictions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_restrictions_vehicle_id'), table_name='vehicle_restrictions')
    op.drop_index(op.f('ix_vehicle_restrictions_status'), table_name='vehicle_restrictions')
    op.drop_index(op.f('ix_vehicle_restrictions_plate_normalized'), table_name='vehicle_restrictions')
    op.drop_table('vehicle_restrictions')
    op.drop_index(op.f('ix_access_permits_vehicle_id'), table_name='access_permits')
    op.drop_index(op.f('ix_access_permits_status'), table_name='access_permits')
    op.drop_index(op.f('ix_access_permits_plate_normalized'), table_name='access_permits')
    op.drop_table('access_permits')
    op.drop_index(op.f('ix_vehicles_unit_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate_normalized'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_owner_person_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###