"""phase45_parking_gate_traffic

Revision ID: 3b394d2c1d9d
Revises: 395a9aba608d
Create Date: 2026-09-16 07:14:43.261863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

revision: str = '3b394d2c1d9d'
down_revision: Union[str, None] = '395a9aba608d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('device_info', sa.String(length=256), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_user_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=True),
    sa.Column('aggregate_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_table('parking_occupancies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parking_space_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('access_event_id', sa.String(length=36), nullable=True),
    sa.Column('occupied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vacated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_occupancies_parking_space_id'), 'parking_occupancies', ['parking_space_id'], unique=False)
    op.create_index(op.f('ix_parking_occupancies_status'), 'parking_occupancies', ['status'], unique=False)
    op.create_index(op.f('ix_parking_occupancies_vehicle_id'), 'parking_occupancies', ['vehicle_id'], unique=False)
    op.create_table('gates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('complex_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('gate_type', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gates_code'), 'gates', ['code'], unique=True)
    op.create_index(op.f('ix_gates_complex_id'), 'gates', ['complex_id'], unique=False)
    op.create_index(op.f('ix_gates_status'), 'gates', ['status'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gate_id', sa.String(length=36), nullable=False),
    sa.Column('device_type', sa.String(length=16), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('protocol', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('configuration', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_gate_id'), 'devices', ['gate_id'], unique=False)
    op.create_table('parking_spaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('complex_id', sa.String(length=36), nullable=True),
    sa.Column('tower_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=16), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=16), nullable=True),
    sa.Column('parking_type', sa.String(length=16), nullable=False),
    sa.Column('map_x', sa.Integer(), nullable=True),
    sa.Column('map_y', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_spaces_code'), 'parking_spaces', ['code'], unique=True)
    op.create_index(op.f('ix_parking_spaces_complex_id'), 'parking_spaces', ['complex_id'], unique=False)
    op.create_index(op.f('ix_parking_spaces_status'), 'parking_spaces', ['status'], unique=False)
    op.create_index(op.f('ix_parking_spaces_tower_id'), 'parking_spaces', ['tower_id'], unique=False)
    op.create_table('plate_recognition_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gate_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('plate_raw', sa.String(length=64), nullable=False),
    sa.Column('plate_normalized', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_image_file_id', sa.String(length=36), nullable=True),
    sa.Column('plate_image_file_id', sa.String(length=36), nullable=True),
    sa.Column('source_event_id', sa.String(length=64), nullable=False),
    sa.Column('processing_status', sa.String(length=16), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'source_event_id', name='uq_plate_dev_src')
    )
    op.create_index(op.f('ix_plate_recognition_events_device_id'), 'plate_recognition_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_plate_recognition_events_gate_id'), 'plate_recognition_events', ['gate_id'], unique=False)
    op.create_index(op.f('ix_plate_recognition_events_plate_normalized'), 'plate_recognition_events', ['plate_normalized'], unique=False)
    op.create_index(op.f('ix_plate_recognition_events_source_event_id'), 'plate_recognition_events', ['source_event_id'], unique=False)
    op.create_table('access_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plate_recognition_event_id', sa.String(length=36), nullable=True),
    sa.Column('gate_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('plate_normalized', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('permit_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('decision_reason', sa.String(length=64), nullable=True),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('offline_created', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_events_decision'), 'access_events', ['decision'], unique=False)
    op.create_index(op.f('ix_access_events_event_time'), 'access_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_access_events_event_type'), 'access_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_access_events_gate_id'), 'access_events', ['gate_id'], unique=False)
    op.create_index(op.f('ix_access_events_idempotency_key'), 'access_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_access_events_plate_normalized'), 'access_events', ['plate_normalized'], unique=False)
    op.create_index(op.f('ix_access_events_vehicle_id'), 'access_events', ['vehicle_id'], unique=False)
    op.create_table('parking_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parking_space_id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('assignment_type', sa.String(length=16), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parking_space_id'], ['parking_spaces.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_assignments_parking_space_id'), 'parking_assignments', ['parking_space_id'], unique=False)
    op.create_index(op.f('ix_parking_assignments_status'), 'parking_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_parking_assignments_unit_id'), 'parking_assignments', ['unit_id'], unique=False)
    op.create_index(op.f('ix_parking_assignments_vehicle_id'), 'parking_assignments', ['vehicle_id'], unique=False)
    op.create_table('parking_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('plate_normalized', sa.String(length=32), nullable=False),
    sa.Column('entry_event_id', sa.String(length=36), nullable=True),
    sa.Column('exit_event_id', sa.String(length=36), nullable=True),
    sa.Column('entry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tariff_id', sa.String(length=36), nullable=True),
    sa.Column('base_amount', sa.BigInteger(), nullable=False),
    sa.Column('discount_amount', sa.BigInteger(), nullable=False),
    sa.Column('penalty_amount', sa.BigInteger(), nullable=False),
    sa.Column('final_amount', sa.BigInteger(), nullable=False),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_sessions_payment_status'), 'parking_sessions', ['payment_status'], unique=False)
    op.create_index(op.f('ix_parking_sessions_plate_normalized'), 'parking_sessions', ['plate_normalized'], unique=False)
    op.create_index(op.f('ix_parking_sessions_status'), 'parking_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_parking_sessions_vehicle_id'), 'parking_sessions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_sessions_vehicle_id'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_status'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_plate_normalized'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_payment_status'), table_name='parking_sessions')
    op.drop_table('parking_sessions')
    op.drop_index(op.f('ix_parking_assignments_vehicle_id'), table_name='parking_assignments')
    op.drop_index(op.f('ix_parking_assignments_unit_id'), table_name='parking_assignments')
    op.drop_index(op.f('ix_parking_assignments_status'), table_name='parking_assignments')
    op.drop_index(op.f('ix_parking_assignments_parking_space_id'), table_name='parking_assignments')
    op.drop_table('parking_assignments')
    op.drop_index(op.f('ix_access_events_vehicle_id'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_plate_normalized'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_idempotency_key'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_gate_id'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_event_type'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_event_time'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_decision'), table_name='access_events')
    op.drop_table('access_events')
    op.drop_index(op.f('ix_plate_recognition_events_source_event_id'), table_name='plate_recognition_events')
    op.drop_index(op.f('ix_plate_recognition_events_plate_normalized'), table_name='plate_recognition_events')
    op.drop_index(op.f('ix_plate_recognition_events_gate_id'), table_name='plate_recognition_events')
    op.drop_index(op.f('ix_plate_recognition_events_device_id'), table_name='plate_recognition_events')
    op.drop_table('plate_recognition_events')
    op.drop_index(op.f('ix_parking_spaces_tower_id'), table_name='parking_spaces')
    op.drop_index(op.f('ix_parking_spaces_status'), table_name='parking_spaces')
    op.drop_index(op.f('ix_parking_spaces_complex_id'), table_name='parking_spaces')
    op.drop_index(op.f('ix_parking_spaces_code'), table_name='parking_spaces')
    op.drop_table('parking_spaces')
    op.drop_index(op.f('ix_devices_gate_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_gates_status'), table_name='gates')
    op.drop_index(op.f('ix_gates_complex_id'), table_name='gates')
    op.drop_index(op.f('ix_gates_code'), table_name='gates')
    op.drop_table('gates')
    op.drop_index(op.f('ix_parking_occupancies_vehicle_id'), table_name='parking_occupancies')
    op.drop_index(op.f('ix_parking_occupancies_status'), table_name='parking_occupancies')
    op.drop_index(op.f('ix_parking_occupancies_parking_space_id'), table_name='parking_occupancies')
    op.drop_table('parking_occupancies')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###