"""phaseE_base_data_person_photo

Revision ID: 7374bae6247e
Revises: 1b4d2025348d
Create Date: 2026-09-16 13:08:54.143634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

revision: str = '7374bae6247e'
down_revision: Union[str, None] = '1b4d2025348d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('photo_file_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_persons_photo_file_id'), 'persons', ['photo_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persons_photo_file_id'), table_name='persons')
    op.drop_column('persons', 'photo_file_id')
    # ### end Alembic commands ###