"""phaseF_base_data_tables

Revision ID: 870b51c3d00d
Revises: 7374bae6247e
Create Date: 2026-09-16 13:21:52.336744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

revision: str = '870b51c3d00d'
down_revision: Union[str, None] = '7374bae6247e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_brands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name_fa', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_brands_name_fa'), 'vehicle_brands', ['name_fa'], unique=True)
    op.create_table('vehicle_colors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name_fa', sa.String(length=32), nullable=False),
    sa.Column('hex_code', sa.String(length=9), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_colors_name_fa'), 'vehicle_colors', ['name_fa'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_colors_name_fa'), table_name='vehicle_colors')
    op.drop_table('vehicle_colors')
    op.drop_index(op.f('ix_vehicle_brands_name_fa'), table_name='vehicle_brands')
    op.drop_table('vehicle_brands')
    # ### end Alembic commands ###