"""phase789_finance_violations

Revision ID: 90db7a4e87e6
Revises: 3b394d2c1d9d
Create Date: 2026-09-16 08:27:11.229471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

revision: str = '90db7a4e87e6'
down_revision: Union[str, None] = '3b394d2c1d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parking_session_id', sa.String(length=36), nullable=True),
    sa.Column('violation_id', sa.String(length=36), nullable=True),
    sa.Column('charge_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charges_parking_session_id'), 'charges', ['parking_session_id'], unique=False)
    op.create_index(op.f('ix_charges_status'), 'charges', ['status'], unique=False)
    op.create_index(op.f('ix_charges_violation_id'), 'charges', ['violation_id'], unique=False)
    op.create_table('financial_adjustments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('adjustment_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_adjustments_entity_id'), 'financial_adjustments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_financial_adjustments_status'), 'financial_adjustments', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference_number', sa.String(length=64), nullable=False),
    sa.Column('payer_person_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('plate_normalized', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('gateway_reference', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_plate_normalized'), 'payments', ['plate_normalized'], unique=False)
    op.create_index(op.f('ix_payments_reference_number'), 'payments', ['reference_number'], unique=True)
    op.create_index(op.f('ix_payments_vehicle_id'), 'payments', ['vehicle_id'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('vehicle_category', sa.String(length=16), nullable=True),
    sa.Column('permit_category', sa.String(length=16), nullable=True),
    sa.Column('free_minutes', sa.Integer(), nullable=False),
    sa.Column('hourly_amount', sa.BigInteger(), nullable=False),
    sa.Column('daily_max_amount', sa.BigInteger(), nullable=True),
    sa.Column('night_amount', sa.BigInteger(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_status'), 'tariffs', ['status'], unique=False)
    op.create_table('violation_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('default_penalty_amount', sa.BigInteger(), nullable=False),
    sa.Column('requires_image', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violation_types_code'), 'violation_types', ['code'], unique=True)
    op.create_table('payment_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('charge_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_allocations_charge_id'), 'payment_allocations', ['charge_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('plate_normalized', sa.String(length=32), nullable=True),
    sa.Column('violation_type_id', sa.String(length=36), nullable=False),
    sa.Column('parking_space_id', sa.String(length=36), nullable=True),
    sa.Column('gate_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('penalty_amount', sa.BigInteger(), nullable=False),
    sa.Column('registered_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['violation_type_id'], ['violation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_plate_normalized'), 'violations', ['plate_normalized'], unique=False)
    op.create_index(op.f('ix_violations_status'), 'violations', ['status'], unique=False)
    op.create_index(op.f('ix_violations_vehicle_id'), 'violations', ['vehicle_id'], unique=False)
    op.create_table('violation_appeals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('violation_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_by', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('review_result', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violation_appeals_violation_id'), 'violation_appeals', ['violation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violation_appeals_violation_id'), table_name='violation_appeals')
    op.drop_table('violation_appeals')
    op.drop_index(op.f('ix_violations_vehicle_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_status'), table_name='violations')
    op.drop_index(op.f('ix_violations_plate_normalized'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_charge_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_violation_types_code'), table_name='violation_types')
    op.drop_table('violation_types')
    op.drop_index(op.f('ix_tariffs_status'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_payments_vehicle_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_plate_normalized'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_financial_adjustments_status'), table_name='financial_adjustments')
    op.drop_index(op.f('ix_financial_adjustments_entity_id'), table_name='financial_adjustments')
    op.drop_table('financial_adjustments')
    op.drop_index(op.f('ix_charges_violation_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_status'), table_name='charges')
    op.drop_index(op.f('ix_charges_parking_session_id'), table_name='charges')
    op.drop_table('charges')
    # ### end Alembic commands ###