"""phaseH2_cad_table_fix

Revision ID: 9929acb7931d
Revises: b89c828ae38b
Create Date: 2026-09-16 22:59:27.905841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

revision: str = '9929acb7931d'
down_revision: Union[str, None] = 'b89c828ae38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###