"""phaseI3_plate_regions

Revision ID: ae1f830b6c93
Revises: 9929acb7931d
Create Date: 2026-09-17 00:37:04.180546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 from sqlalchemy.dialects import postgresql

revision: str = 'ae1f830b6c93'
down_revision: Union[str, None] = '9929acb7931d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plate_regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plate_code', sa.String(length=4), nullable=False),
    sa.Column('province', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('letters', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plate_regions_plate_code'), 'plate_regions', ['plate_code'], unique=False)
    op.drop_index('ix_cad_parking_spots_parking_code', table_name='cad_parking_spots')
    op.drop_index('ix_cad_parking_spots_status', table_name='cad_parking_spots')
    op.drop_table('cad_parking_spots')
    op.add_column('vehicles', sa.Column('plate_letter', sa.String(length=4), nullable=True))
    op.add_column('vehicles', sa.Column('plate_province_code', sa.String(length=4), nullable=True))
    op.add_column('vehicles', sa.Column('plate_province', sa.String(length=64), nullable=True))
    op.add_column('vehicles', sa.Column('plate_city', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'plate_city')
    op.drop_column('vehicles', 'plate_province')
    op.drop_column('vehicles', 'plate_province_code')
    op.drop_column('vehicles', 'plate_letter')
    op.create_table('cad_parking_spots',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('parking_code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('source_drawing', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('source_layer', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('source_entity_handle', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('polygon_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('center_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('center_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rotation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('parking_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cad_parking_spots_pkey')
    )
    op.create_index('ix_cad_parking_spots_status', 'cad_parking_spots', ['status'], unique=False)
    op.create_index('ix_cad_parking_spots_parking_code', 'cad_parking_spots', ['parking_code'], unique=True)
    op.drop_index(op.f('ix_plate_regions_plate_code'), table_name='plate_regions')
    op.drop_table('plate_regions')
    # ### end Alembic commands ###