"""phaseH_cad_parking_spots

Revision ID: b89c828ae38b
Revises: 870b51c3d00d
Create Date: 2026-09-16 22:51:06.792867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

revision: str = 'b89c828ae38b'
down_revision: Union[str, None] = '870b51c3d00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###